language: c
notifications:
 irc:
  channels: "anathema.us.nu#anathema"
  use_notice: true
  skip_join: true
compiler:
 - clang
 - gcc
before_install:
 - sudo apt-get update -qq
install:
 - sudo apt-get install -y xsltproc docbook-xsl zlib1g-dev libncursesw5-dev
 - sudo apt-get install -y libgtk-3-dev libpango1.0-dev
before_script:
 - mkdir build
 - cd build
script:
 - cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DWITH_GTK=ON -DBUILD_TESTING=ON
 - make
 - cpack -G DEB
 - ctest
