language: c
notifications:
 irc:
  channels: "anathema.us.nu#anathema"
  use_notice: true
  skip_join: true
env:
 global:
  - secure: "N6CD6ynyF+YpxhyQ6UkRz0pDQiM7jVqP5o5xkXuOP4I7+58Fq6ThEB/LK0NLIwHH9MVIyNWovlf5HHhkaLUW7qVFpmcxM3AGL0lAqaGIbZ8uCVuoL7ERtqpJ3uPl6hrt+tdUaSVvXQgteuTDgprQRICCDBxR/1s7/qBAL1T6VK0="
addons:
 coverity_scan:
  project:
   name: "pjanouch/sdtui"
   description: "StarDict terminal UI"
  notification_email: p.janouch@gmail.com
  build_command_prepend: "cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_GTK=ON -DBUILD_TESTING=ON"
  build_command: "make"
  branch_pattern: coverity_scan
compiler:
 - clang
 - gcc
before_install:
 - sudo apt-get update -qq
install:
 - sudo apt-get install -y xsltproc docbook-xsl zlib1g-dev libncursesw5-dev
 - sudo apt-get install -y libgtk-3-dev libpango1.0-dev libicu-dev
before_script:
 - mkdir build
 - cd build
script:
 - cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DWITH_GTK=ON -DBUILD_TESTING=ON
 - make
 - cpack -G DEB
 - ctest
